Repository Ddukbbegi/backend, pull requests merged in 2025-04, with the labels that each got.

#35 [Feat] #23 : 가게 도메인 구현
  src/main/java/com/ddukbbegi/api/store/entity/Store.java
  src/main/java/com/ddukbbegi/api/store/enums/DayOfWeek.java
  src/main/java/com/ddukbbegi/api/store/enums/DayOfWeekListConverter.java
  src/main/java/com/ddukbbegi/api/store/enums/StoreStatus.java
Labels: enhancement

#43 [Feat] #25: 가게 CRUD 구현
  src/main/java/com/ddukbbegi/api/store/controller/StoreController.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreBasicInfoDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreOperationInfoDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreOrderSettingsInfo.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreRegisterRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateBasicInfoRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateOperationInfoRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateOrderSettingsRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateStatusRequest.java
  src/main/java/com/ddukbbegi/api/store/dto/response/OwnerStoreResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StoreIdResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StorePageItemResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StoreRegisterAvailableResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StoreResponseDto.java
  src/main/java/com/ddukbbegi/api/store/entity/Store.java
  src/main/java/com/ddukbbegi/api/store/enums/StoreCategory.java
  src/main/java/com/ddukbbegi/api/store/enums/StoreStatus.java
  src/main/java/com/ddukbbegi/api/store/repository/StoreRepository.java
  src/main/java/com/ddukbbegi/api/store/service/StoreService.java
  src/main/java/com/ddukbbegi/api/store/util/TimeRangeParser.java
  src/main/java/com/ddukbbegi/common/component/ResultCode.java
Labels: enhancement

#51 [Refactor] #49 : 가게 도메인 코드 리팩토링
  src/main/java/com/ddukbbegi/api/store/controller/StoreController.java
  src/main/java/com/ddukbbegi/api/store/controller/StoreOwnerController.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreBasicInfoDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreOperationInfoDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreOrderSettingsInfo.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreRegisterRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateBasicInfoRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateOperationInfoRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateOrderSettingsRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreUpdateStatusRequest.java
  src/main/java/com/ddukbbegi/api/store/dto/response/OwnerStoreResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StoreIdResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StorePageItemResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StoreRegisterAvailableResponseDto.java
  src/main/java/com/ddukbbegi/api/store/service/StoreService.java
Labels: enhancement

#72 [Feat] #27 : Store 도메인 관련 테스트 코드 작성
  .gitignore
  src/main/java/com/ddukbbegi/api/store/dto/request/RequestStoreBasicInfo.java
  src/main/java/com/ddukbbegi/api/store/dto/response/OwnerStoreResponseDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/ResponseStoreBasicInfo.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StorePageItemResponseDto.java
  src/main/java/com/ddukbbegi/api/store/enums/DayOfWeekListConverter.java
  src/main/java/com/ddukbbegi/api/store/enums/StoreCategory.java
  src/main/java/com/ddukbbegi/api/store/enums/StoreStatus.java
  src/main/java/com/ddukbbegi/api/store/repository/StoreRepository.java
  src/main/java/com/ddukbbegi/api/store/service/StoreService.java
  src/main/java/com/ddukbbegi/api/store/util/TimeRangeParser.java
  src/main/java/com/ddukbbegi/common/component/ResultCode.java
  src/test/java/com/ddukbbegi/api/store/dto/request/AbstractValidatorTest.java
  src/test/java/com/ddukbbegi/api/store/dto/request/RequestStoreBasicInfoTest.java
  src/test/java/com/ddukbbegi/api/store/dto/request/RequestStoreOperationInfoTest.java
  src/test/java/com/ddukbbegi/api/store/enums/DayOfWeekListConverterTest.java
  src/test/java/com/ddukbbegi/api/store/enums/StoreCategoryTest.java
  src/test/java/com/ddukbbegi/api/store/repository/StoreRepositoryTest.java
  src/test/java/com/ddukbbegi/api/store/scheduler/StoreStatusSchedulerTest.java
  src/test/java/com/ddukbbegi/api/store/service/StoreServiceTest.java
  src/test/java/com/ddukbbegi/api/store/service/StoreStatusResolveServiceTest.java
  src/test/java/com/ddukbbegi/api/store/util/TimeRangeFormatterTest.java
  src/test/java/com/ddukbbegi/api/store/util/TimeRangeParserTest.java
  src/test/java/com/ddukbbegi/support/config/TestAuditorConfig.java
  src/test/java/com/ddukbbegi/support/fixture/StoreFixture.java
Labels: enhancement

#73 [Feat] #71 : Order 도메인 관련 동시성 제어
  src/main/java/com/ddukbbegi/api/menu/entity/Menu.java
  src/main/java/com/ddukbbegi/api/menu/repository/MenuRepository.java
  src/main/java/com/ddukbbegi/api/order/dto/request/OrderCreateRequestDto.java
  src/main/java/com/ddukbbegi/api/order/entity/Order.java
  src/main/java/com/ddukbbegi/api/order/repository/OrderRepository.java
  src/main/java/com/ddukbbegi/api/order/service/OrderService.java
  src/main/java/com/ddukbbegi/api/review/repository/ReviewRepository.java
  src/main/java/com/ddukbbegi/common/component/ResultCode.java
  src/test/java/com/ddukbbegi/api/order/service/OrderConcurrencyTest.java
  src/test/java/com/ddukbbegi/api/order/service/OrderServiceTest.java
Labels: enhancement

#82 [Feat] #80 : Aop 기능 추가
  src/main/java/com/ddukbbegi/api/store/controller/StoreOwnerController.java
  src/main/java/com/ddukbbegi/common/config/aop/Owner.java
  src/main/java/com/ddukbbegi/common/config/aop/OwnerAccessLoggingAspect.java
  src/test/java/com/ddukbbegi/api/review/ReviewServiceTest.java
Labels: enhancement

#86 [Fix] Merge 후 빌드 되지 않는 문제 해결
  src/main/java/com/ddukbbegi/api/point/controller/PointController.java
  src/test/java/com/ddukbbegi/api/order/service/OrderConcurrencyTest.java
  src/test/java/com/ddukbbegi/api/order/service/OrderServiceTest.java
Labels: bug

#98 [Feat] #84 : 인수 테스트 작성 완료
  build.gradle
  src/main/java/com/ddukbbegi/api/menu/dto/response/AllMenuResponseDto.java
  src/main/java/com/ddukbbegi/api/order/service/OrderService.java
  src/main/java/com/ddukbbegi/api/review/service/ReviewService.java
  src/main/java/com/ddukbbegi/api/store/dto/request/RequestStoreBasicInfo.java
  src/main/java/com/ddukbbegi/api/store/dto/request/RequestStoreOperationInfo.java
  src/main/java/com/ddukbbegi/api/store/dto/request/StoreRegisterRequestDto.java
  src/main/java/com/ddukbbegi/api/store/dto/response/StorePageItemResponseDto.java
  src/main/java/com/ddukbbegi/api/store/service/StoreService.java
  src/main/java/com/ddukbbegi/api/store/service/StoreStatusResolveService.java
  src/main/java/com/ddukbbegi/common/component/ResultCode.java
  src/test/java/com/ddukbbegi/DdukbbegiApplicationTests.java
  src/test/java/com/ddukbbegi/acceptance/AdminAcceptanceTest.java
  src/test/java/com/ddukbbegi/acceptance/MenuAcceptanceTest.java
  src/test/java/com/ddukbbegi/acceptance/OrderAcceptanceTest.java
  src/test/java/com/ddukbbegi/acceptance/ReviewAcceptanceTest.java
  src/test/java/com/ddukbbegi/acceptance/StoreAcceptanceTest.java
  src/test/java/com/ddukbbegi/acceptance/support/AcceptanceTestSupport.java
  src/test/java/com/ddukbbegi/api/review/service/ReviewServiceTest.java
  src/test/java/com/ddukbbegi/api/store/service/StoreServiceTest.java
  src/test/java/com/ddukbbegi/support/config/TestContainersConfig.java
  src/test/java/com/ddukbbegi/support/fixture/MenuFixture.java
  src/test/java/com/ddukbbegi/support/fixture/OrderFixture.java
  src/test/java/com/ddukbbegi/support/fixture/ReviewFixture.java
  src/test/java/com/ddukbbegi/support/fixture/StoreFixture.java
  src/test/resources/application-testcontainers.yml
Labels: documentation, enhancement
